# Generated by Django 5.2 on 2025-09-05 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabrief',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='planner.campaign'),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='media_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='planner.mediaplan'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='planner_cam_tenant__b53567_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaplan',
            index=models.Index(fields=['campaign', 'status'], name='planner_med_campaig_83743c_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringreport',
            index=models.Index(fields=['media_plan', 'generated_at'], name='planner_mon_media_p_6a9fc3_idx'),
        ),
    ]
