# Generated by Django 5.2 on 2025-09-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaplan',
            name='slots',
        ),
        migrations.AddField(
            model_name='campaign',
            name='advertiser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='daypart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.daypart'),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='price_per_spot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.show'),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='spots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaplan',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='mediaplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('locked', 'Locked'), ('rejected', 'Rejected')], default='draft', max_length=32),
        ),
    ]
