# Generated by Django 5.2 on 2025-09-05 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_set_uploaded_at_default'),
        ('stations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringreport',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_reports', to='planner.campaign'),
        ),
        migrations.AddField(
            model_name='monitoringreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='monitoring_reports/'),
        ),
        migrations.AlterField(
            model_name='monitoringreport',
            name='media_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='planner.mediaplan'),
        ),
        migrations.CreateModel(
            name='MonitoringImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='monitoring_imports/')),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airtime', models.DateTimeField(blank=True, null=True)),
                ('spots_aired', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ambiguous', 'Ambiguous')], default='unmatched', max_length=32)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.campaign')),
                ('daypart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.daypart')),
                ('media_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.mediaplan')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.show')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('monitoring_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planner.monitoringimport')),
            ],
        ),
        migrations.AddIndex(
            model_name='monitoringimport',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='planner_mon_tenant__74903a_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringentry',
            index=models.Index(fields=['tenant', 'campaign', 'media_plan', 'processed'], name='planner_mon_tenant__63afb6_idx'),
        ),
    ]
