# Generated by Django 5.2 on 2025-09-12 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_monitoringreport_campaign_monitoringreport_file_and_more'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_length', models.IntegerField(help_text='Block length in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.show')),
            ],
        ),
    ]
